# 프로젝트 Root 폴더
# 프로젝트Root/docker-compose.yml
version: '3.2'

services: 
  frontend:
    image: frontend-vue
    build:
      context: frontend/
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /home/ubuntu/docker-volume/ssl:/var/www/html
    container_name: "frontend"
  
  backend:
    image: backend-spring
    build:
      context: backend/jpmp/
      dockerfile: dockerfile
    ports:
      - "8443:8443"  

    volumes:
      - /home/ubuntu/docker-volume/ssl:/root
    container_name: "backend"
